[general]
host = "0.0.0.0"
port = 8080
root = "/srv"
log-level = "error"
compression = true
compression-level = "default"
cache-control-headers = true
security-headers = true
page-fallback = "/srv/index.html"
health = true
threads-multiplier = 1

[advanced]
[[advanced.headers]]
source = "**/*"
[advanced.headers.headers]
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
Cross-Origin-Embedder-Policy = "require-corp"
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Resource-Policy = "same-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'; object-src 'none'"
